# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Minimal
email: mimimi@blah.com
description: "Este é um blog feito com Jekyll para o CodeG."
baseurl: "/minimal-blog"
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mimi_twitter
github_username:  blah.github

# Build settings
markdown: kramdown
#permalink: /:categories/:year/:month/:day/:title
#permalink: /:year/:month/:day/:title
permalink: /:title
